[package]
name = "builder"
version = "0.1.0"
authors = ["vaiklol <samokatanet@gmail.com>"]
edition = "2018"

[dependencies]
syn = { version="0.15", features=["derive", "full"] }
quote = "0.6.3"

[lib]
proc-macro = true